### ISSUE TITLE
Editing a news should be disabled

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.plugin.ws#13]
When editing a news from EPFL News, in the lower righ a box "News Channels" is shown:
![image](https://user-images.githubusercontent.com/176002/34563732-2728efc8-f154-11e7-8d53-4be9d79baf7b.png)

e.g. see [this new](https://sti-test.epfl.ch/wp-admin/post.php?post=272&action=edit).

**Comment by domq** [comment]
Fixed in fb3fd9f46a1c2d8b2
